### PR TITLE
Fix minor warnings from GCC in C++17/20 mode

### PR DESCRIPTION
**Pull request by angriman**
Fixes new gcc C++17/20 warnings.

### CODE REVIEW

**Review by avdgrinten — APPROVED** [review]
LGTM. What are the warnings that are fixed? Specifically, why does GCC complain about the `i ? y : x`? This seems to only be a stylistic issue to me (the old code expresses `i != 0` while the new code expresses `i > 0`).

The "unsigned cannot be negative" fixes make sense of course.

**Comment by angriman** [comment]
Yes `i ? y : x` is just stylistic, I just find `i > 0 ? y : x` clearer to read.

**Comment by avdgrinten** [comment]
What's the warning that GCC produced for the former?

**Comment by angriman** [comment]
It produces `-Wunused-result` in `ttmathobjects.hpp` for:
```
value.empty();
```
And `-Wtype-limits` for the first condition in:
```
assert(levelIdx >= 0 && levelIdx < this->size());
```

**Comment by avdgrinten** [comment]
So the ternary condition does not produce any warning and it was just refactored anyway?

**Comment by angriman** [comment]
Yes it's a stylistic change (the only one in this PR), I just find it clearer to write it like that.

**Pull request merged**
