### PR TITLE
Make CI fail on failed python test, fix failing python tests

### PR DESCRIPTION
**Pull request by angriman**
The python interface of `EdmondsKarp` does not properly inherit from `Algorithm`, and thus the `run` method is not visible (#721).
The CI has system has been fixed so that it fails when a python test fails.
Further fixes in `test_graphio.py`.

### CODE REVIEW

**Comment by fabratu** [comment]
Why this is not triggered is currently investigated. One problem is, that "fast failing" is not active by default (even though the documentation of Github Actions) states it. Will post a PR soon.

**Comment by michitux** [comment]
@angriman I think you need to remove the `__dealloc__`-method, too, or at least it is superfluous, depending on the order in which they are executed it might lead to a double free.

**Comment by angriman** [comment]
@michitux thanks, that's probably what causes the segfault.

**Comment by avdgrinten** [comment]
This PR contains a bunch of unrelated CI changes; these need to be extracted to a separate PR.

**Comment by angriman** [comment]
The CI changes have been included so that the fixes that this PR applies are actually tested. Our CI system had a bug that made the CI succeed even it some python tests failed, I updated the description of the PR to clarify this.

**Review by fabratu — APPROVED** [review]

**Pull request merged**
