### PR TITLE
Simple doc fixes

### PR DESCRIPTION
**Pull request by darabos**
Hi!
I'm an engineer on https://github.com/lynxkite/lynxkite. It's an open-source graph analytics tool with a GUI. For the next release we plan to make a bunch of algorithms from NetworKit available. I have wrapped 24 so far and we love everything about NetworKit. ❤️ 

My first step was to list the algorithms and figure out what is what, so I looked a lot at the docs. I found some mistakes that were easy to fix and that's this PR.

| Before | After |
|---|---|
|image|image|

I will make more small fixes if I find anything.

But as I wrap the algorithms I also write the LynxKite documentation for them. I try to include a loosely worded description of what the algorithm does and explain why someone would want to use it. It's a bit different from the NetworKit docs style. E.g. my description for HyperbolicGenerator is way more verbose than the NetworKit page:

- https://networkit.github.io/dev-docs/cpp_api/classNetworKit_1_1HyperbolicGenerator.html
- https://github.com/lynxkite/lynxkite/blob/master/web/app/help/operations/create-hyperbolic-random-graph.asciidoc

(You can see more in https://github.com/lynxkite/lynxkite/pull/102/files.)

We would be happy to contribute these descriptions to NetworKit if there's interest. (We are AGPL licensed, but we can dual license these docs under MIT.) But I also understand if you want to keep NetworKit docs more concise. I just wanted to float this idea!

Thanks very much for maintaining this excellent project!

### CODE REVIEW

**Comment by fabratu** [comment]
Hi darabos,

thanks for the pull request and your kind words!

Regarding your suggestions: Our documentation can sure benefit from descriptions for algorithms. It is something we first have to discuss internally, since there are also some other things on the agenda for documentation.

**Review by fabratu — APPROVED** [review]

**Comment by avdgrinten** [comment]
Merging this to get it into the next release.

**Comment by fabratu** [comment]
@darabos If you read this - we would be happy to benefit from contribution towards our documentation :) Best way would be, if you open a PR including either all or a subset of the algorithmic descriptions. For licensing: if dual-licensing is possible for your project, we go with MIT. If there are questions, we can discuss them here or in the PR. I also followed you on twitter (same nick).

**Comment by darabos** [comment]
> @darabos If you read this - we would be happy to benefit from contribution towards our documentation :) Best way would be, if you open a PR including either all or a subset of the algorithmic descriptions.

All right! I'm now adding another batch to LynxKite (`LocalCommunityEvaluation` subclasses). But after that I'll take a break from integration and send a PR with the docs.

**Comment by fabratu** [comment]
Perfect - thanks!

**Pull request merged**
