### PR TITLE
Bug fix: group closeness local search

### PR DESCRIPTION
**Pull request by angriman**
The local-search approximation algorithm should evaluate all swaps. However, the current implementation excludes leaves of the DAG, which leads to potentially incorrect results and random failures of `CentralityGTest.testGroupClosenessLocalSearch`.

### CODE REVIEW

**Comment by avdgrinten** [comment]
Does this affect grow-shrink etc? What is the DAG here?

**Comment by angriman** [comment]
These changes do not affect GS, but the error probably affects the non-local GS. I have to look at GS more carefully.

**Comment by angriman** [comment]
Non-extended GS should consider leaves of the DAG as candidates for swaps as well, so I also applied the fix to non-extended GS.

**Review by avdgrinten — APPROVED** [review]
LGTM.

**Pull request merged**
