### PR TITLE
Update gitignore

### PR DESCRIPTION
**Pull request by angriman**
Ignore `include/ttmath` in `.gitignore`.

### CODE REVIEW

**Comment by fabratu** [comment]
Hm, since the source-files of `ttmath` are a part of the github-repo - shouldn't we keep them tracked in case we change them?

**Comment by angriman** [comment]
`include/ttmath` is generated when NetworKit is installed, the actual library is stored in `extlibs/ttmath`. The same is already done for `tlx`, so it does not appear as an untracked file in `git status`.

**Comment by fabratu** [comment]
Ah, you are right.

**Review by fabratu — APPROVED** [review]
LGTM.

**Pull request merged**
