### PR TITLE
Refactor: Math libraries

### PR DESCRIPTION
**Pull request by angriman**
- Remove usage of deprecated `math.h` C library
- the "ttmath" library is added as a git submodule

### CODE REVIEW

**Comment by avdgrinten** [comment]
`math.h` is not really deprecated, is it? It's just the C version of `<cmath>`.

**Comment by avdgrinten** [comment]
Maybe the 2nd and 3rd commit should be squashed together, such that we do not end up in a situation where NetworKit does not build.

**Comment by angriman** [comment]
Ah true, I misinterpreted the documentation about "C compatibility headers" https://en.cppreference.com/w/cpp/header

**Review by avdgrinten — APPROVED** [review]
LGTM.

**Pull request merged**
