### PR TITLE
Fix clang-tidy errors

### PR DESCRIPTION
**Pull request by angriman**
Building NetworKit with:

```
cmake -DNETWORKIT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_STANDARD=17 -DNETWORKIT_CLANG_TIDY=ON
```

fails because of `modernize-use-emplace`. Shouldn't these error be caught by our CI?

### CODE REVIEW

**Comment by fabratu** [comment]
Yes, they should be caught. Maybe that is version related. For `clang-tidy` we still use version 15.X. Which compiler / llvm-tools version did you use?

**Comment by angriman** [comment]
I used the llvm clang version `16.0.5`.

**Comment by fabratu** [comment]
That likely would explain it. Given the time, could you also raise the clang-tidy version (alongside with the Ubuntu image) on the CI?[1] 

[1] https://github.com/networkit/networkit/blob/master/.github/workflows/ci.yml#L281

**Comment by angriman** [comment]
Yes it seems to be due to the version, I upgraded to llvm 16 in a separate branch and the clang-tidy job is failing: https://github.com/angriman/networkit/actions/runs/5535930376/jobs/10102912358.

**Review by fabratu — APPROVED** [review]

**Pull request merged**
