### PR TITLE
Fix unformatted file

### PR DESCRIPTION
**Pull request by angriman**
I broke the formatting of a file while resolving a conflict. This PR re-formats the affected file.

### CODE REVIEW

**Review by fabratu — APPROVED** [review]

**Comment by avdgrinten** [comment]
Why did this get past CI?

**Comment by angriman** [comment]
Because I used the GitHub web UI to resolve a conflict, which did not discard the review.

**Comment by avdgrinten** [comment]
Moral of the story: don't do that ;D.

**Comment by angriman** [comment]
Exactly, I'll merge this now to fix CI. These are trivial changes anyway.

**Pull request merged**
