### PR TITLE
Fix GlobalThresholdFilter

### PR DESCRIPTION
**Pull request by angriman**
This PR fixes two main issues:
- Templated methods of `EdgeScore` were implemented in the `.cpp` file. They have been moved to the header file.
- `GlobalThresholdFilter` now also support directed and weighted graphs. In the previous implementation the graph was transformed to an undirected graph with default edgeweights without throwing any warnings or errors. If the input graph is directed, this yields a discrepancy in the number of edges in the resulting graph (as reported in #499).

### CODE REVIEW

**Comment by michitux** [comment]
Why do you move the implementation of `EdgeScore` into the header? What is the issue you are trying to solve here? The intention of the template is only to support both `double` and `count` as scores, and both are instantiated explicitly in the `.cpp` file.

**Comment by avdgrinten** [comment]
If that is supposed to be the case, we need `extern template EdgeScore<double>;` in the header to avoid ODR violations (if I interpret the standard correctly here: right now the template is instantiated both implicitly *and* explicitly, in different TUs). In that case, we should also add a `static_assert` with a meaningful error message. But why do you want the class to be restricted to `double` and `count` in the first place?

**Comment by michitux** [comment]
This `extern template EdgeScore<double>;` might be a good idea, but I do not think it is strictly necessary as it has only been introduced in C++11. There are no edge scores in NetworKit that use any other type. Also, the Cython interface needs to explicitly list all types, so if more types shall be supported, the Cython interface would need to be adjusted. The basic idea here is to reduce compile time. Without this, as far as I understand, the template will be instantiated every time it is used, e.g., in `_NetworKit.pyx`.

**Comment by michitux** [comment]
I have searched a bit more, `extern template` is only required when the template is fully defined in the header. If it is only declared, as it is without this PR, `extern template` has no effect. See e.g. [here](https://stackoverflow.com/questions/8130602/using-extern-template-c11/59614090#59614090). Adding a `static_assert` could be a good idea, but apart from that I do not see anything that should be changed here.

**Comment by avdgrinten** [comment]
Isn't the class definition complete? For a class to be complete, all members must be complete - but functions do not need to be defined.

**Comment by avdgrinten** [comment]
Contrary to the example in the linked SO answer, the EdgeScore class does have function definitions for some functions (namely, inherited methods from the base classes).

**Comment by fabratu** [comment]
@angriman @avdgrinten @michitux 
In the course of the (honestly very intriguing) discussion about the nature of templates/compilers, maybe this PR should be split. The second part about `GlobalThresholdFilter` fixes an active issue and should be integrated. 

To add a review for this part: Looks good to me, only a (minor) question:
- Should we add a test, that compares `numberOfEdges()` against an actual count ... or is this automatically resolved by not converting the graph?

**Comment by angriman** [comment]
I see the point of having the implementation of `EdgeScore` in a separate file, I dropped that commit (which was also out of the scope of this PR).

**Pull request merged**
