### PR TITLE
Fix unused variable warnings.

### PR DESCRIPTION
**Pull request by angriman**
- Remove unused variables
- Use `tlx::unused` for variables used only in debug mode
- Use pre-increment instead of post-increment where possible

### CODE REVIEW

**Comment by fabratu** [comment]
In addition to the changes mentioned, you also change `&` to `&&`. The reasoning is, that logic comparison should be done with logic operators?

Also, can you split the changes concerning `unused` and the ones concerning style/opt?

**Comment by angriman** [comment]
> In addition to the changes mentioned, you also change `&` to `&&`. The reasoning is, that logic comparison should be done with logic operators?

Yes, we were getting this warning: https://clang.llvm.org/docs/DiagnosticsReference.html#wbitwise-instead-of-logical

> Also, can you split the changes concerning `unused` and the ones concerning style/opt?

Sure!

**Comment by fabratu** [comment]
Hm, I should have been more attentive concerning your PR. Seems I fixed a lot of problems for the second time. In addition, switching to pre-increment also seems to make some `unused` markings unnecessary.

After a rebase, we can merge this PR right away. Sorry for creating even more work ;)

**Comment by angriman** [comment]
No worries, conflicts were minimal. Now it should be ok!

**Review by fabratu — APPROVED** [review]

**Pull request merged**
