### PR TITLE
setup.py: add --external-tlx option

### PR DESCRIPTION
**Pull request by SeekingMeaning**
This is used in https://github.com/Homebrew/homebrew-core/pull/67184

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by fabratu** [comment]
Thanks for support with the brew-package and for posting this PR! :)

**Review by avdgrinten — APPROVED** [review]
LGTM.

**Comment by fabratu** [comment]
Added a new test to check both external core cpp library and tlx.

**Review by angriman — APPROVED** [review]

**Review by avdgrinten — CHANGES_REQUESTED** [review]
I think the CI run for this feature should be merged into an existing CI run.

**Comment by fabratu** [comment]
@avdgrinten Integrated the test into the existing workflow.

**Review by avdgrinten — APPROVED** [review]
LGTM.

**Comment by avdgrinten** [comment]
Merging this now, to get it into the next release.

**Pull request merged**
