### PR TITLE
RFC: README: Add contribution guidelines

### PR DESCRIPTION
**Pull request by avdgrinten**
To be applied after the resolution of #329. Please discuss what we should add to the guidelines.

### CODE REVIEW

**Comment by angriman** [comment]
What about fixing a maximum number of characters per line?

**Comment by avdgrinten** [comment]
I think we should have a soft (i.e., not automatically enforced) limit of 100 characters.

**Comment by manpen** [comment]
There's already a [DevGuide](https://networkit.github.io/dev-docs/DevGuide.html) which should either be the only place or a strict superset (i.e., the `README.md` contains a summary).
So I suggest to add these rules (esp. name conventions) also to the DevGuides and place a link the guide in the Readme.

**Comment by avdgrinten** [comment]
What I dislike about the DevGuide is that 90% of it consists of common Git practices. It contains a lot of noise and is sometimes even inaccurate. I would like to collect essential contribution guidelines (and there should not be so many) in the README.md or in a CONTRIBUTING.md. The DevGuide can link to that document.

**Pull request closed without merging**
