### PR TITLE
Fix a bunch of "unused" warnings

### PR DESCRIPTION
**Pull request by manpen**
Fix remaining "unused" warnings.

### CODE REVIEW

**Comment by angriman** [comment]
Thank you for fixing this.

I see that in `AuxRandomBenchmark.cpp` there are several comments like `// TODO: replace with google benchmark infrastructure`. Do we actually want to use the [google/benchmark](https://github.com/google/benchmark) infrastructure in the future?

**Comment by avdgrinten** [comment]
I am not convinced about the use of `volatile` to prevent optimization. In GCC and Clang, one can use inline assembly constraints to force the compiler to keep a variable around and to commit changes to memory:

```c
asm volatile ("" : : "p"(&x) : "memory");
```
(Demo: https://godbolt.org/z/blMf01)

This should be more robust than a volatile write. However, I do not know if MSVC has comparable syntax. Maybe it's worthwhile to check what other projects (Google Benchmark?) do.

In any case, I think that this `doNotOptimize()` function should not be specific to this test. Instead, it should be moved to a global header (with the comment that it should only be used for benchmarking).

**Comment by manpen** [comment]
@avdgrinten This is exactly the implementation of Google Benchmark. In issue #213, I said that I would add Google Benchmark and CMake infrastructure, but did not come around to do so. My suggestion would be to leave the PR as is (it's the same implementation we had before, only without warnings) and, to add Google Benchmark soon.

**Comment by avdgrinten** [comment]
I think the question whether Google Benchmark is the correct solution for NetworKit is not clearly answered yet. Google Benchmark seems to be aimed at microbenchmarks (100s to millions of iterations / second), whereas NetworKit's algorithms often require multiple seconds to run (on interesting instances).

**Pull request merged**
