### PR TITLE
Fix compiler warnings and treat warnings as errors in CI

### PR DESCRIPTION
**Pull request by manpen**
We've come a long way in improving code quality and removing warnings. Unfortunately, we sometimes merge code to `Dev` which causes compiler warnings, or more recent compilers add additional warnings which remain unfixed for some time. 

This PR fixes exactly this type of warnings. Additionally it introduces the CMake flag `NETWORKIT_WARNINGS_AS_ERRORS` (default: OFF) and enables it during CI. As the name suggests, this treats compiler warnings as errors (with the exception of deprecation warnings).

### CODE REVIEW

**Comment by avdgrinten** [comment]
This is a great idea. Indeed, it took a lot of effort to remove all warnings. Thank you for the patch, i will review it shortly.

**Comment by manpen** [comment]
Due to merge conflicts, I need to rebase the PR and now had to fix warnings that were introduced in the mean time. I hope that CI now runs through.

**Comment by angriman** [comment]
Did the rebase invalidate @avdgrinten approval?

**Comment by manpen** [comment]
I believe so. @avdgrinten approved it on the 27th

**Pull request merged**
