### PR TITLE
Migration from Travis CI to Github Actions

### PR DESCRIPTION
**Pull request by fabratu**
This migrates all tests from Travis CI to Github Actions. Motivation for this PR is the recently introduced price model for Travis CI and reoccuring test errors due to (likely) image problems.

- Windows tests are still done by appveyor
- Since Actions are only triggered / visible on the default branch, here is a preview from my fork: https://github.com/fabratu/networkit/actions (The documentation build fails, since the deployment token is not added to the fork)
- Added secrets for deployments to project settings

First impressions:
- There is more caching involved. Setup time therefore takes less time for consecutive runs.
- More concurrent jobs / cores per job.
- Reduced runtime: ~2h Travis CI vs. ~25min Github Actions

### CODE REVIEW

**Comment by angriman** [comment]
Shouldn't you delete the `.travis.yml` file?

**Comment by avdgrinten** [comment]
Why do we move scripts to their own files instead of keeping them inline (not necessarily a bad change, I am just asking for the rationale).

**Comment by fabratu** [comment]
`.travis.yml`:
I should have mentioned it in the first comment: We haven't decided yet whether to have both systems for a small period of time and delete the Travis stuff once everything runs fine. So I wanted to leave this for discussion.

External scripts:
Github Actions doesn't support reusing scripts. Therefore to avoid having the same script several times, the core and full build are moved to an external script. I decided to do the same for the other builds (coverage, doc, clang-tidy) in order to have consistency.

**Comment by fabratu** [comment]
Besides: I would vote for having both tools for a short time.

**Comment by angriman** [comment]
Yes I think it makes sense to do so.

**Review by angriman — APPROVED** [review]

**Comment by avdgrinten** [comment]
Please add proper shebangs to the scripts. Maybe also reconsider the directory structure: do we really need multiple subdirectories in .github/workflows? Isn't one subdirectory for scripts + utils enough? Otherwise, this looks good to me.

**Review by avdgrinten — DISMISSED** [review]
LGTM now.

**Comment by fabratu** [comment]
Thanks! Except that it doesn't work anymore (some folder access error). Looking into it.

**Comment by avdgrinten** [comment]
By the way, why do we still use AppVeyor for Windows builds?

**Comment by angriman** [comment]
I think we could migrate the Windows builds to GitHub actions in a separate PR.

**Comment by avdgrinten** [comment]
Let's get this merged as soon as it works.

**Comment by fabratu** [comment]
Technically it works, but for macOS 11 (Big Sur) some tests in Aux seems to fail. I have yet no idea, what this is about. The tests worked with the previous beta image, but not with the most recent one.

Should I first sort this out or do we want to merge the PR before that?

**Comment by avdgrinten** [comment]
Travis does not test MacOS 11 either, so we can just drop these configurations / mark them as "allowed to fail" (if that is possible).

**Comment by fabratu** [comment]
Ok, for now I added `continue-on-error` (which I think is what you suggest). You can see [here](https://github.com/fabratu/networkit/actions), that some actions fail. However if tagged with this option, the whole CI-pipeline will still be true. 

macOS 11.0 will get mandatory in a different PR.

**Review by angriman — APPROVED** [review]
Looks fine to me now

**Pull request merged**
