### PR TITLE
Documentation: add missing parameters in community-module, add missing csbridge-module

### PR DESCRIPTION
**Pull request by fabratu**
- Addresses  #838. By adding the function header as the first line of the doc, this enables rendering of missing parameters. This PR only fixes this for the `community`-module. For the PRs to become not too big, other modules will be addressed in other PRs.
- Fix several documentation strings, which are not compliant with sphinx-automodule (`community`-module)
- Add missing function documentation (`community`-module)
- Add missing function documentation in C++ counterparts
- Add missing `csbridge`-module to Python-documentation

### CODE REVIEW

**Review by angriman — COMMENTED** [review]
The documentation of some functions like `getImbalance` seems to be missing in the cpp source as well. Can you document also the cpp source?

**Comment by avdgrinten** [comment]
Do you mean the C++ headers? We do not document the source files, right?

**Comment by angriman** [comment]
Sorry,  I meant the headers.

**Comment by fabratu** [comment]
Agreed and added. Hope I didn't miss anything.

**Review by angriman — APPROVED** [review]

**Pull request merged**
