### PR TITLE
Fix case configuration in clang-tidy

### PR DESCRIPTION
**Pull request by angriman**
As described in #653

### CODE REVIEW

**Comment by avdgrinten** [comment]
There are way too many violations to enable the check. We should change the configuration without enabling the check.

**Comment by angriman** [comment]
True, I disabled them.

**Comment by avdgrinten** [comment]
They are still enabled in the latest commit (and clang-tidy produces 80k lines of warnings).

**Review by avdgrinten — APPROVED** [review]
LGTM.

**Pull request merged**
