### PR TITLE
clang-format sources of io

### PR DESCRIPTION
**Pull request by angriman**
This is a continuation of #803

### CODE REVIEW

**Comment by angriman** [comment]
Windows builds seem to be broken, the error message is: `C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winnt.h(169): fatal error C1189: #error:  "No Target Architecture"
`

**Comment by angriman** [comment]
Actually, the error is because clang-format changed the order of the `#include`s. Some files have `#include <windows.h>`, which must be placed before other headers that depend on `windows.h`, I'll fix that.

**Review by fabratu — APPROVED** [review]
LGTM.

**Comment by avdgrinten** [comment]
Won't this be reverted by running clang-format again?

**Comment by angriman** [comment]
> Tried it locally and nothing is changed. I think the additional new line is preventing this.

As @fabratu wrote, I added an empty line between `#include<windows.h>` and the other headers; this prevents clang-format from moving it below other headers.

**Pull request merged**
