### PR TITLE
graph.pyx: adjust datatypes to be compatible with numpy2.0

### PR DESCRIPTION
**Pull request by PetholzA**
re-upload of #1234 where the commits have been split

### CODE REVIEW

**Comment by fabratu** [comment]
Thanks, please also adjust the README: `Python3 (3.8 or higher is supported)`

**Comment by PetholzA** [comment]
> Thanks, please also adjust the README: `Python3 (3.8 or higher is supported)`

This is already contained in the PR.

**Comment by fabratu** [comment]
Thanks, now the edit is shown for me. Likely some caching issues.

**Review by fabratu — APPROVED** [review]

**Comment by fabratu** [comment]
Merging this directly, since this also influences other PRs and fixes issues on CI.

**Pull request merged**
