### PR TITLE
Add MTXGraphReader

### PR DESCRIPTION
**Pull request by friedagerharz**
Adding a reader for the [Matrix Market Format](https://networkrepository.com/mtx-matrix-market-format.html).

- [ ] add tests

### CODE REVIEW

**Comment by CharJon** [comment]
Hi @friedagerharz , what is the MatrixMarketReader from io/MatrixMarketReader.hpp missing?

**Comment by friedagerharz** [comment]
> Hi @friedagerharz , what is the MatrixMarketReader from io/MatrixMarketReader.hpp missing?

Hi, I created this reader for use with the b-Suitor algorithm (#1132). For this algorithm I need the graph structure in `graph/Graph.hpp`. Instead of opting to implement a conversion from `CSRGeneralMatrix` to `Graph` I decided to implement the reader directly to avoid this extra step.

**Comment by CharJon** [comment]
> > Hi @friedagerharz , what is the MatrixMarketReader from io/MatrixMarketReader.hpp missing?
> 
> Hi, I created this reader for use with the b-Suitor algorithm (#1109). For this algorithm I need the graph structure in `graph/Graph.hpp`. Instead of opting to implement a conversion from `CSRGeneralMatrix` to `Graph` I decided to implement the reader directly to avoid this extra step.

Does ```MatrixTools::matrixToGraph(mat);``` work for you?

**Comment by friedagerharz** [comment]
> matrixToGraph

Yes, great thank you! Overlooked this function.

**Comment by fabratu** [comment]
@friedagerharz @CharJon While `matrixToGraph` is a useful function, having a direct reader for a graph data structure is saves time and resources. Also, this enables to have the reader in Python directly. I suggest calling the class `MatrixMarketGraphReader` to distinguish between both variants.

**Comment by fabratu** [comment]
Will close this PR, the functionality will be finalized in PR #1236.

**Pull request closed without merging**
